### ISSUE TITLE
RC13 throws an exception which was not happening on RC12

### ISSUE THREAD

**Issue by Macarse** [arturbosch/detekt#1476]
```
Analyzing 'X.kt' led to an exception.
The original exception message was: java.lang.NoSuchFieldError: LONG_STRING_TEMPLATE_ENTRY
Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Mac OS X'.

If the exception message does not help, please feel free to create an issue on our github page.
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
com.github.shyiko.ktlint.ruleset.standard.StringTemplateRule.visit(StringTemplateRule.kt:29)
io.gitlab.arturbosch.detekt.formatting.FormattingRule.apply(FormattingRule.kt:64)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2$$special$$inlined$forEach$lambda$1.invoke(KtLintMultiRule.kt:84)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2$$special$$inlined$forEach$lambda$1.invoke(KtLintMultiRule.kt:44)
io.gitlab.arturbosch.detekt.api.MultiRule.runIfActive(MultiRule.kt:27)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:84)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:44)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visitTokens(KtLintMultiRule.kt:96)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visit(KtLintMultiRule.kt:82)
io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:36)
io.gitlab.arturbosch.detekt.api.RuleSet.accept(RuleSet.kt:36)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:60)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:23)
io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:27)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
com.github.shyiko.ktlint.ruleset.standard.StringTemplateRule.visit(StringTemplateRule.kt:29)
io.gitlab.arturbosch.detekt.formatting.FormattingRule.apply(FormattingRule.kt:64)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2$$special$$inlined$forEach$lambda$1.invoke(KtLintMultiRule.kt:84)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2$$special$$inlined$forEach$lambda$1.invoke(KtLintMultiRule.kt:44)
io.gitlab.arturbosch.detekt.api.MultiRule.runIfActive(MultiRule.kt:27)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:84)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule$visit$2.invoke(KtLintMultiRule.kt:44)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visitTokens(KtLintMultiRule.kt:96)
io.gitlab.arturbosch.detekt.formatting.KtLintMultiRule.visit(KtLintMultiRule.kt:82)
io.gitlab.arturbosch.detekt.api.BaseRule.visitFile(BaseRule.kt:36)
io.gitlab.arturbosch.detekt.api.RuleSet.accept(RuleSet.kt:36)
io.gitlab.arturbosch.detekt.core.Detektor.analyze(Detektor.kt:60)
io.gitlab.arturbosch.detekt.core.Detektor.access$analyze(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:29)
io.gitlab.arturbosch.detekt.core.Detektor$run$1$$special$$inlined$map$lambda$1.invoke(Detektor.kt:14)
io.gitlab.arturbosch.detekt.core.TasksKt$runAsync$1.invoke(Tasks.kt:23)
io.gitlab.arturbosch.detekt.core.TasksKt$task$1.get(Tasks.kt:27)
java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
```

**Comment by 3flex** [comment]
This is an error with ktlint, but was fixed in ktlint 0.30.0. That version should be pulled in as a dependency...

Can you see which ktlint version is pulled in as a dependency by running `gradlew dependencies`?

**Comment by schalkms** [comment]
Can you please also post your settings so that we can narrow down the problem?
As @3flex mentioned the same error should be fixed with ktlint 0.30.0.

**Comment by Macarse** [comment]
mmm I don't longer see the error :(

My gradlew dependencies:
```
detektPlugins - The detektPlugins libraries to be used for this project.
\--- io.gitlab.arturbosch.detekt:detekt-formatting:1.0.0-RC13
     +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21
     |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.21
     |    \--- org.jetbrains:annotations:13.0
     +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.21
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    +--- org.jetbrains.kotlin:kotlin-script-runtime:1.3.21
     |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.21
     |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    \--- org.jetbrains.intellij.deps:trove4j:1.0.20181211
     +--- io.gitlab.arturbosch.detekt:detekt-api:1.0.0-RC13
     |    +--- org.jetbrains.kotlin:kotlin-compiler-embeddable:1.3.21 (*)
     |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.21 (*)
     |    +--- org.yaml:snakeyaml:1.23
     |    \--- org.jetbrains.kotlin:kotlin-reflect:1.3.21 (*)
     +--- com.github.shyiko.ktlint:ktlint-ruleset-standard:0.30.0
     \--- com.github.shyiko.ktlint:ktlint-core:0.30.0
```
I see 0.30.0 now.

Perhaps it would help to add the klint version to the:
```Running detekt '1.0.0-RC13' on Java '1.8.0_201-b09' on OS 'Mac OS X'.```
log

**Comment by schalkms** [comment]
What did you do to fix the issue? @Macarse

**Comment by Macarse** [comment]
tbh, I don't know.

I am still not using RC13 because of https://github.com/arturbosch/detekt/issues/1475 

I created this ticket after increasing gradle wrapper version to 5.1, and running detekt. Perhaps I didn't update the `io.gitlab.arturbosch.detekt:detekt-formatting` the first time I tried it 🤷‍♂️ 

This should be closed.
